-- VERTEX SUPPLY CHAIN ANALYSIS
-- DATABASE SCHEMA

-- 1. SUPPLIERS TABLE
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID VARCHAR(20) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(100),
    SUPPLIER_COUNTRY VARCHAR(100),
    SUPPLIER_RATING DECIMAL(3,1),
    LEAD_TIME_DAYS INT
);


-- 2. PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    SUPPLIER_ID VARCHAR(20),
    UNIT_COST DECIMAL(10,2),
    SELLING_PRICE DECIMAL(10,2),
    FOREIGN KEY (SUPPLIER_ID)
        REFERENCES SUPPLIERS(SUPPLIER_ID)
);


-- 3. SHIPMENTS TABLE
CREATE TABLE SHIPMENTS (
    SHIPMENT_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_ID VARCHAR(20),
    SHIPMENT_DATE DATE,
    WAREHOUSE VARCHAR(100),
    QUANTITY_RECEIVED INT,
    QUANTITY_DAMAGED INT,
    TRANSPORT_COST DECIMAL(12,2),
    FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
);
