-- VERTEX SUPPLY CHAIN ANALYSIS
-- LOAD DATA INTO MYSQL

-- Load suppliers
LOAD DATA LOCAL INFILE 'path/to/suppliers.csv'
INTO TABLE SUPPLIERS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- Load products
LOAD DATA LOCAL INFILE 'path/to/productskl.csv'
INTO TABLE PRODUCTS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- Load shipments
LOAD DATA LOCAL INFILE 'path/to/shipments.csv'
INTO TABLE SHIPMENTS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
