-- BUSINESS KPIs

-- 1. TOTAL INVENTORY RECEIVED
SELECT
SUM(QUANTITY_RECEIVED) AS NO_OF_INVENTORY
FROM SHIPMENTS;

-- 2. TOTAL DAMAGED PRODUCTS RECEIVED
SELECT
SUM(QUANTITY_DAMAGED) AS NO_OF_DAMAGED_PRODUCTS
FROM SHIPMENTS;

-- 3. DAMAGED PRODUCTS%
SELECT
ROUND(SUM(QUANTITY_DAMAGED)/SUM(QUANTITY_RECEIVED)*100,2) AS DAMAGED_RATE
FROM SHIPMENTS;

-- 4. TOTAL TRANSPORTATION COST
SELECT
SUM(TRANSPORT_COST) AS TRANSAPORT_COST
FROM SHIPMENTS;

-- 5. MONTHS VS INVENTORY RECEIVED
SELECT
MONTHNAME(SHIPMENT_DATE) AS MONTHS,
SUM(QUANTITY_RECEIVED) AS INVENTORY
FROM SHIPMENTS
GROUP BY MONTHS
ORDER BY INVENTORY DESC;

-- 6. WAREHOUSES VS INVENTORY RECEIVED
SELECT
WAREHOUSE,
SUM(QUANTITY_RECEIVED) AS INVENTORY
FROM SHIPMENTS
GROUP BY WAREHOUSE
ORDER BY INVENTORY DESC;

-- 7. TOTAL UNDAMAGED PRODUCTS RECEIVED (NET UNITS RECEIVED)
SELECT
(SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED)) AS NET_UNITS_RECEIVED
FROM SHIPMENTS;

-- 8. PRODUCTS BY QUANTITY RECEIVED
SELECT
PRODUCT_NAME,
SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS
FROM PRODUCTS
JOIN SHIPMENTS
ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
GROUP BY PRODUCT_NAME;

-- 9. TOTAL INVENTORY COST
SELECT
SUM((TOTAL_UNITS)*UNIT_COST) AS TOTAL_INVENTORY_COST
FROM
(
    SELECT
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    UNIT_COST,
    SELLING_PRICE
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    PRODUCT_NAME,
    UNIT_COST,
    SELLING_PRICE
) AS SUBQUERY;

-- 10. POTENTIAL REVENUE
-- IF ALL PRODUCTS RECEIVED WERE TO BE SOLD
SELECT
SUM((TOTAL_UNITS)*SELLING_PRICE) AS POTENTIAL_REVENUE
FROM
(
    SELECT
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SELLING_PRICE
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    PRODUCT_NAME,
    SELLING_PRICE
) AS SUBQUERY;

-- 11. GROSS PROFIT
SELECT
(SUM((TOTAL_UNITS * SELLING_PRICE)) -
 SUM(TOTAL_UNITS * UNIT_COST)) AS GROSS_PROFIT
FROM
(
    SELECT
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SELLING_PRICE,
    UNIT_COST
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    PRODUCTS.PRODUCT_ID,
    PRODUCT_NAME,
    SELLING_PRICE,
    UNIT_COST
) AS SUBQUERY;

-- 12. NET REVENUE (SELLABLE REVENUE)
SELECT
SUM(NET_UNITS * SELLING_PRICE) AS NET_REVENUE
FROM
(
    SELECT
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
    SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
    SELLING_PRICE,
    UNIT_COST
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    PRODUCT_NAME,
    SELLING_PRICE,
    UNIT_COST
) AS SUBQUERY;

-- 13. REVENUE LOST DUE TO DAMAGED PRODUCTS
SELECT
POTENTIAL_REVENUE - NET_REVENUE AS REVENUE_LOST
FROM
(
    SELECT
    SUM(NET_UNITS * SELLING_PRICE) AS NET_REVENUE,
    SUM((TOTAL_UNITS)*SELLING_PRICE) AS POTENTIAL_REVENUE
    FROM
    (
        SELECT
        PRODUCT_NAME,
        SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
        SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
        SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
        SELLING_PRICE,
        UNIT_COST
        FROM PRODUCTS
        JOIN SHIPMENTS
        ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
        GROUP BY
        PRODUCT_NAME,
        SELLING_PRICE,
        UNIT_COST
    ) AS SUBQUERY
) AS CALC;

-- 14. NET PROFIT
SELECT
SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) AS NET_PROFIT
FROM
(
    SELECT
    PRODUCTS.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
    SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
    SELLING_PRICE,
    UNIT_COST,
    (SUM(QUANTITY_RECEIVED) * UNIT_COST) AS INVENTORY_COST,
    ((SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED)) * SELLING_PRICE) AS NET_REVENUE,
    SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    PRODUCTS.PRODUCT_ID,
    PRODUCT_NAME,
    SELLING_PRICE,
    UNIT_COST
) AS SUBQUERY;

-- 15. PROFIT MARGIN
SELECT
ROUND(
SUM(NET_PROFIT) / SUM(NET_REVENUE) * 100,
2
) AS PROFIT_MARGIN
FROM
(
    SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(S.QUANTITY_DAMAGED) AS DAMAGED_UNITS,
    SUM(S.QUANTITY_RECEIVED) - SUM(S.QUANTITY_DAMAGED) AS NET_UNITS,
    P.SELLING_PRICE,
    P.UNIT_COST,
    SUM(S.QUANTITY_RECEIVED) * P.UNIT_COST AS INVENTORY_COST,
    (SUM(S.QUANTITY_RECEIVED) - SUM(S.QUANTITY_DAMAGED))
        * P.SELLING_PRICE AS NET_REVENUE,
    SUM(S.TRANSPORT_COST) AS TOTAL_TRANSPORT_COST,
    (
        (SUM(S.QUANTITY_RECEIVED) - SUM(S.QUANTITY_DAMAGED))
        * P.SELLING_PRICE
    )
    - (SUM(S.QUANTITY_RECEIVED) * P.UNIT_COST)
    - SUM(S.TRANSPORT_COST) AS NET_PROFIT
    FROM PRODUCTS P
    JOIN SHIPMENTS S
    ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.SELLING_PRICE,
    P.UNIT_COST
) AS PROFIT;
