-- PRODUCT ANALYSIS

-- 1. TOP 5 MOST PROFITABLE PRODUCTS
SELECT
PRODUCT_NAME,
NET_PROFIT,
RANKINGS
FROM
(
    SELECT
    PRODUCT_NAME,
    SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) AS NET_PROFIT,
    DENSE_RANK() OVER (
        ORDER BY
        SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) DESC
    ) AS RANKINGS
    FROM
    (
        SELECT
        PRODUCT_NAME,
        SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
        SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
        SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
        SELLING_PRICE,
        UNIT_COST,
        (SUM(QUANTITY_RECEIVED) * UNIT_COST) AS INVENTORY_COST,
        ((SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED)) * SELLING_PRICE) AS NET_REVENUE,
        SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST
        FROM PRODUCTS
        JOIN SHIPMENTS
        ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
        GROUP BY
        PRODUCT_NAME,
        SELLING_PRICE,
        UNIT_COST
    ) AS SUBQUERY
    GROUP BY
    PRODUCT_NAME
) AS PROFITS
WHERE RANKINGS <= 5;


-- 2. LOSS-MAKING PRODUCTS
SELECT
PRODUCT_NAME,
SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) AS NET_PROFIT,
DENSE_RANK() OVER (
    ORDER BY
    SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) DESC
) AS RANKINGS
FROM
(
    SELECT
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
    SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
    SELLING_PRICE,
    UNIT_COST,
    (SUM(QUANTITY_RECEIVED) * UNIT_COST) AS INVENTORY_COST,
    ((SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED)) * SELLING_PRICE) AS NET_REVENUE,
    SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    PRODUCT_NAME,
    SELLING_PRICE,
    UNIT_COST
) AS SUBQUERY
GROUP BY
PRODUCT_NAME
HAVING NET_PROFIT < 0;


-- 3. CATEGORY BY NET REVENUE
SELECT
CATEGORY,
SUM(NET_UNITS * SELLING_PRICE) AS NET_REVENUE
FROM
(
    SELECT
    CATEGORY,
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
    SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
    SELLING_PRICE,
    UNIT_COST
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    CATEGORY,
    PRODUCT_NAME,
    SELLING_PRICE,
    UNIT_COST
) AS SUBQUERY
GROUP BY
CATEGORY;


-- 4. PRODUCTS BY PROFIT MARGIN
SELECT
PRODUCT_NAME,
ROUND(
    SUM(NET_PROFIT) / SUM(NET_REVENUE) * 100,
    2
) AS PROFIT_MARGIN
FROM
(
    SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(S.QUANTITY_DAMAGED) AS DAMAGED_UNITS,
    SUM(S.QUANTITY_RECEIVED) - SUM(S.QUANTITY_DAMAGED) AS NET_UNITS,
    P.SELLING_PRICE,
    P.UNIT_COST,
    SUM(S.QUANTITY_RECEIVED) * P.UNIT_COST AS INVENTORY_COST,
    (SUM(S.QUANTITY_RECEIVED) - SUM(S.QUANTITY_DAMAGED))
        * P.SELLING_PRICE AS NET_REVENUE,
    SUM(S.TRANSPORT_COST) AS TOTAL_TRANSPORT_COST,
    (
        (SUM(S.QUANTITY_RECEIVED) - SUM(S.QUANTITY_DAMAGED))
        * P.SELLING_PRICE
    )
    - (SUM(S.QUANTITY_RECEIVED) * P.UNIT_COST)
    - SUM(S.TRANSPORT_COST) AS NET_PROFIT
    FROM PRODUCTS P
    JOIN SHIPMENTS S
    ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.SELLING_PRICE,
    P.UNIT_COST
) AS PROFIT
GROUP BY
PRODUCT_NAME;


-- 5. PRODUCTS BY DAMAGE RATE
SELECT
PRODUCT_NAME,
ROUND(
    SUM(DAMAGED_UNITS) / SUM(TOTAL_UNITS) * 100,
    2
) AS DAMAGE_RATE
FROM
(
    SELECT
    PRODUCT_NAME,
    SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
    SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS
    FROM PRODUCTS
    JOIN SHIPMENTS
    ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
    GROUP BY
    PRODUCT_NAME
) AS DAMAGE
GROUP BY
PRODUCT_NAME
ORDER BY
DAMAGE_RATE DESC;
