-- SUPPLIER ANALYSIS

-- 1. LOSS-MAKING SUPPLIERS
SELECT
SUPPLIER_NAME,
NET_PROFIT,
RANKINGS
FROM
(
    SELECT
    SUPPLIER_NAME,
    SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) AS NET_PROFIT,
    DENSE_RANK() OVER (
        ORDER BY
        SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) DESC
    ) AS RANKINGS
    FROM
    (
        SELECT
        SUPPLIER_NAME,
        SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
        SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
        SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
        SELLING_PRICE,
        UNIT_COST,
        (SUM(QUANTITY_RECEIVED) * UNIT_COST) AS INVENTORY_COST,
        ((SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED)) * SELLING_PRICE) AS NET_REVENUE,
        SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST
        FROM PRODUCTS
        JOIN SUPPLIERS
        ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
        JOIN SHIPMENTS
        ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
        GROUP BY
        SUPPLIER_NAME,
        SELLING_PRICE,
        UNIT_COST
    ) AS SUBQUERY
    GROUP BY
    SUPPLIER_NAME
) AS PROFITS
WHERE NET_PROFIT <= 0;


-- 2. TOP 5 PROFITABLE SUPPLIERS
SELECT
SUPPLIER_NAME,
NET_PROFIT,
RANKINGS
FROM
(
    SELECT
    SUPPLIER_NAME,
    SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) AS NET_PROFIT,
    DENSE_RANK() OVER (
        ORDER BY
        SUM(NET_REVENUE) - SUM(INVENTORY_COST) - SUM(TOTAL_TRANSPORT_COST) DESC
    ) AS RANKINGS
    FROM
    (
        SELECT
        SUPPLIER_NAME,
        SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
        SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
        SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
        SELLING_PRICE,
        UNIT_COST,
        (SUM(QUANTITY_RECEIVED) * UNIT_COST) AS INVENTORY_COST,
        ((SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED)) * SELLING_PRICE) AS NET_REVENUE,
        SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST
        FROM PRODUCTS
        JOIN SUPPLIERS
        ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
        JOIN SHIPMENTS
        ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
        GROUP BY
        SUPPLIER_NAME,
        SELLING_PRICE,
        UNIT_COST
    ) AS SUBQUERY
    GROUP BY
    SUPPLIER_NAME
) AS PROFITS
WHERE RANKINGS <= 5;


-- 3. SUPPLIER PERFORMANCE OVER TIME
SELECT
SUPPLIER_NAME,
MONTHS,
SUM(NET_REVENUE) OVER (
    PARTITION BY SUPPLIER_NAME
    ORDER BY NET_REVENUE DESC
) AS NET_REVENUE
FROM
(
    SELECT
    SUPPLIER_NAME,
    MONTHS,
    SUM(NET_UNITS * SELLING_PRICE) AS NET_REVENUE
    FROM
    (
        SELECT
        SUPPLIER_NAME,
        PRODUCT_NAME,
        MONTHNAME(SHIPMENT_DATE) AS MONTHS,
        SUM(QUANTITY_RECEIVED) AS TOTAL_UNITS,
        SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
        SUM(QUANTITY_RECEIVED) - SUM(QUANTITY_DAMAGED) AS NET_UNITS,
        SELLING_PRICE,
        UNIT_COST
        FROM SUPPLIERS
        JOIN PRODUCTS
        ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
        JOIN SHIPMENTS
        ON SHIPMENTS.PRODUCT_ID = PRODUCTS.PRODUCT_ID
        GROUP BY
        SUPPLIER_NAME,
        PRODUCT_NAME,
        MONTHS,
        SELLING_PRICE,
        UNIT_COST
    ) AS SUBQUERY
    GROUP BY
    SUPPLIER_NAME,
    MONTHS
) AS SUBS;


-- 4. SUPPLIERS BY DAMAGED UNITS
SELECT
SUPPLIER_NAME,
SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS
FROM SUPPLIERS
JOIN PRODUCTS
ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
JOIN SHIPMENTS
ON SHIPMENTS.PRODUCT_ID = PRODUCTS.PRODUCT_ID
GROUP BY
SUPPLIER_NAME
ORDER BY
DAMAGED_UNITS DESC;


-- 5. SUPPLIERS BY TRANSPORTATION COST
SELECT
SUPPLIER_NAME,
SUM(TRANSPORT_COST) AS TOTAL_TRANSPORT_COST
FROM SUPPLIERS
JOIN PRODUCTS
ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
JOIN SHIPMENTS
ON SHIPMENTS.PRODUCT_ID = PRODUCTS.PRODUCT_ID
GROUP BY
SUPPLIER_NAME
ORDER BY
TOTAL_TRANSPORT_COST DESC;
