-- WAREHOUSE ANALYSIS

-- 1. WAREHOUSES BY INVENTORY RECEIVED
SELECT
WAREHOUSE,
SUM(QUANTITY_RECEIVED) AS INVENTORY_RECEIVED
FROM SHIPMENTS
GROUP BY
WAREHOUSE
ORDER BY
INVENTORY_RECEIVED DESC;


-- 2. WAREHOUSES BY NET REVENUE
SELECT
WAREHOUSE,
SUM(
    (QUANTITY_RECEIVED - QUANTITY_DAMAGED)
    * SELLING_PRICE
) AS NET_REVENUE
FROM SHIPMENTS
JOIN PRODUCTS
ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
GROUP BY
WAREHOUSE
ORDER BY
NET_REVENUE DESC;


-- 3. WAREHOUSES BY DAMAGED UNITS
SELECT
WAREHOUSE,
SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS
FROM SHIPMENTS
GROUP BY
WAREHOUSE
ORDER BY
DAMAGED_UNITS DESC;


-- 4. WAREHOUSE DAMAGE RATE
SELECT
WAREHOUSE,
ROUND(
    SUM(QUANTITY_DAMAGED) /
    SUM(QUANTITY_RECEIVED) * 100,
    2
) AS DAMAGE_RATE
FROM SHIPMENTS
GROUP BY
WAREHOUSE
ORDER BY
DAMAGE_RATE DESC;


-- 5. MONTHLY SHIPMENT PERFORMANCE
SELECT
MONTHNAME(SHIPMENT_DATE) AS MONTHS,
SUM(QUANTITY_RECEIVED) AS INVENTORY_RECEIVED,
SUM(QUANTITY_DAMAGED) AS DAMAGED_UNITS,
SUM(QUANTITY_RECEIVED - QUANTITY_DAMAGED) AS NET_UNITS_RECEIVED
FROM SHIPMENTS
GROUP BY
MONTHS
ORDER BY
INVENTORY_RECEIVED DESC;


-- 6. MONTHLY NET REVENUE
SELECT
MONTHNAME(SHIPMENT_DATE) AS MONTHS,
SUM(
    (QUANTITY_RECEIVED - QUANTITY_DAMAGED)
    * SELLING_PRICE
) AS NET_REVENUE
FROM SHIPMENTS
JOIN PRODUCTS
ON PRODUCTS.PRODUCT_ID = SHIPMENTS.PRODUCT_ID
GROUP BY
MONTHS
ORDER BY
NET_REVENUE DESC;
